spring:
  thymeleaf:
    cache: false
  redis:
    host: 127.0.0.1
    port: 6379
  application:
    name: weather-collection
server:
  port: 8081
eureka:
  client:
    service-url:
      default-zone: http://127.0.0.1:8761/eureka/